[default]
access_token = ''
client_credentials = '128541e2-c497-4aab-a415-6b4252082334'
client_secret = '18oOJDH0wWBoFjVoW1pdETl0loHSMn4Hjag3ni43uHs'
environment = 'mypurecloud.ie'
oauth_token_data = '{"access_token":"gdVKSg5dJCPvMG8wRSsvXMywZs0XZc1hxIODbJLLIswtLfnV-PBKWTHpXvd2NWSsBt3Ppy0G5XWqj3NF4wvDag","token_type":"bearer","expires_in":86399,"error":"","oauth_token_expiry":"2023-05-31T18:47:32+03:00"}'

[hm_fbt]
access_token = ''
client_credentials = '10b3fcd7-ce45-42d8-9f6d-5ab33a8adee4'
client_secret = 'xvEZ3EpjAG_G0guY_9UsLJgYcVOiaMGQ9HPvtt4Jzdc'
environment = 'mypurecloud.de'
oauth_token_data = '{"access_token":"9TF4BOOwZrmfBtFbC8ZmbvaVlqDU-QnhY0c5v0M-fShfL7mZgIN3g6EU6ClSA89QSvdIY4-1-fdzesKXNwo-Uw","token_type":"bearer","expires_in":86399,"error":"","oauth_token_expiry":"2023-05-31T15:37:04+03:00"}'

[hm_ost]
access_token = ''
client_credentials = 'fce73ed5-3a40-4a10-a141-1482563ef5bc'
client_secret = 'AsGhtIVuT5zzzAD-yBBu_I5h7BxU4YYdsu2ogM3ZPsE'
environment = 'mypurecloud.de'
oauth_token_data = '{"access_token":"7pr6rFEicEx6ZQJ-GvfN4hbaWuiF1NEEoRVRHukup3s60YW9UCqPrA5WnqgfwyAIa5TKIE2ui1vAyqPVahJgBA","token_type":"bearer","expires_in":86399,"error":"","oauth_token_expiry":"2023-04-21T19:03:33+03:00"}'

[hsbc]
access_token = ''
client_credentials = '02f7ab9d-4cfe-41fb-a24f-8483fc646f60'
client_secret = 'FdhT2FRsluQ2eSN5gAjPq33IgqbqQovlhlNlUq59kWc'
environment = 'euw2.pure.cloud'
oauth_token_data = '{"access_token":"skc7AdjoQSSpDSiRdWMXaNKLDe1Nof-AHx8L12txCUcE76a_OhBun9ZMcHB8uq47OW_-OlzYqD-81lrKx783uw","token_type":"bearer","expires_in":86399,"error":"","oauth_token_expiry":"2023-05-31T17:47:03+03:00"}'

[hsbc-devorg]
access_token = ''
client_credentials = '6c5820fe-80e1-4713-9e17-29eade2e8044'
client_secret = 'nbdgABMw0beVWNaFvik6NYgWjwivDJChpyoaa8Pne_g'
environment = 'euw2.pure.cloud'
oauth_token_data = '{"access_token":"olSP4GWPt9NmaEYRaYCPRGC5zI5enPC3x7zpDoPgg9kaZs8UkhMaaDDI8ggyZyFTiVMyOHbQ1iZuL0PfTftOLg","token_type":"bearer","expires_in":86399,"error":"","oauth_token_expiry":"2023-05-31T19:00:53+03:00"}'
